included:
- Sources
line_length:
  warning: 165
  ignores_comments: true
large_tuple:
  warning: 3
disabled_rules:
  - colon
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - pattern_matching_keywords
