name: Upload artifact
on:
  release:
    types: [published]
jobs:
  publish_brew:
    name: Publish to Homebrew
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Update Homebrew formula
        run: |
          brew update
          pushd $(brew --repository)/Library/Taps/$HOMEBREW_TAP_REPOSITORY
          git config --local user.name "IBLinter Bot"
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote set-url origin git@github.com:$HOMEBREW_TAP_REPOSITORY
          popd
          git checkout ${GITHUB_REF#refs/heads/}
          make publish_brew
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_TAP_REPOSITORY: homebrew/homebrew-core
  publish_pods:
    name: Publish to CocoaPods
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build portable_iblinter.zip
        run: make portable_zip
      - name: Upload portable_zip for Release assets
        run: ./script/upload_artifact.sh ./portable_iblinter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update CocoaPods spec
        run: make publish_pods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
