name: Release flow
on: create
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Git config
        run: |
          git config --local user.name "IBLinter Bot"
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout ${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version
        if: github.event.ref_type == 'branch'
        run: |
          REF_PATTERN="refs/heads/release/*"
          case "$GITHUB_REF" in
            "")
              echo "\$GITHUB_REF is not set"
              exit 1
              ;;
            $REF_PATTERN)
              echo "$GITHUB_REF matches $REF_PATTERN"
              ;;
            *)
              echo "$GITHUB_REF does not match $REF_PATTERN"
              exit 0
          esac
          RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}
          make bump_version $RELEASE_VERSION
          git push origin HEAD
      - uses: actions/github-script@0.2.0
        if: github.event.ref_type == 'branch'
        with:
          github-token: ${{github.token}}
          script: |
            if (/^.*release\/.+/.test(context.payload.ref)) {
              const version = context.payload.ref.replace(/^.*release\/(.+)/, '$1')
              await github.pulls.create({
                ...context.repo,
                head: context.payload.ref,
                base: "master",
                title: "Release " + version,
                body: "New release tag will be pushed automatically after this PR is merged"
              })
            }
