name: Release flow
on: create
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Git config
        run: |
          git config --local user.name "IBLinter Bot"
          git config --local user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version
        if: github.event.ref_type == "branch"
        run: |
          REF_PATTERN="refs/heads/release/*"
          case "$GITHUB_REF" in
            "")
              echo "\$GITHUB_REF is not set"
              exit 1
              ;;
            $REF_PATTERN)
              echo "$GITHUB_REF matches $REF_PATTERN"
              ;;
            *)
              echo "$GITHUB_REF does not match $REF_PATTERN"
              exit 0
          esac
          RELEASE_VERSION=$(echo $GITHUB_REF | sed "s/^.*release\///")
          make bump_version $RELEASE_VERSION
          git push origin HEAD
      - uses: actions/github-script@0.2.0
        if: github.event.ref_type == "branch"
        with:
          github-token: ${{github.token}}
          script: |
            if (/^.*release\/.+/.test(context.payload)) {
              github.pulls.create({
                ...context.repo,
                base: context.payload.ref,
                title: "Release ${context.payload.ref.replace(/.*release\/(.+)/, '$1')}"
                body: "New release tag will be pushed automatically after this PR is merged"
              })
            }
